name: Deploy Student Preview
on:
  push:
    branches:
      - teresa # Change this to your student's branch name
  workflow_dispatch:  # <--- Add this line!
permissions:
  contents: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: teresa

      - name: Deploy to Subfolder 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder she is working in (usually the root)
          target-folder: preview # The subfolder name for her site
          branch: gh-pages # This should match your deployment branch
